<?php


namespace App\Template\Loader;


use php_user_filter;

class ClosureCompiler extends php_user_filter
{
    protected $appendedClosure = false;

    public function filter($in, $out, &$consumed, $closing)
    {
        parent::filter($in, $out, $consumed, $closing); // TODO: Change the autogenerated stub
    }
}
